-- USE [arrangement-db]

-- ALTER TABLE [Events]
-- DROP CONSTRAINT PK__Events__3214EC0755A65ACD;
-- --PK name for Dev
-- ALTER TABLE [Events]
-- DROP CONSTRAINT DF__Events__Id__7E37BEF6;
-- ALTER TABLE [Events]
-- ADD CONSTRAINT PK__Events__3214EC0755A65ACD PRIMARY KEY (Guid);

-- Find PK name using this command:
-- SELECT * 
-- FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
-- WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
